# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/gui/delete.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deletedialog(object):
    def setupUi(self, deletedialog):
        deletedialog.setObjectName("deletedialog")
        deletedialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("G:/gui\\ff.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        deletedialog.setWindowIcon(icon)
        deletedialog.setStyleSheet("color: rgb(200, 200, 200);\n"
"font: 75 10pt \"Consolas\";\n"
"background-color: rgb(0, 0, 0);")
        self.buttonBox = QtWidgets.QDialogButtonBox(deletedialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(deletedialog)
        self.label.setGeometry(QtCore.QRect(170, 10, 61, 16))
        self.label.setObjectName("label")
        self.chatroom = QtWidgets.QLineEdit(deletedialog)
        self.chatroom.setGeometry(QtCore.QRect(70, 130, 256, 32))
        self.chatroom.setClearButtonEnabled(True)
        self.chatroom.setObjectName("chatroom")
        self.status = QtWidgets.QTextBrowser(deletedialog)
        self.status.setGeometry(QtCore.QRect(0, 280, 128, 16))
        self.status.setStyleSheet("color: rgb(255, 0, 0);")
        self.status.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.status.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.status.setObjectName("status")

        self.retranslateUi(deletedialog)
        self.buttonBox.accepted.connect(deletedialog.accept) # type: ignore
        self.buttonBox.rejected.connect(deletedialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(deletedialog)

    def retranslateUi(self, deletedialog):
        _translate = QtCore.QCoreApplication.translate
        deletedialog.setWindowTitle(_translate("deletedialog", "Delete"))
        self.label.setText(_translate("deletedialog", "[Delete]"))
        self.chatroom.setPlaceholderText(_translate("deletedialog", " Enter Chatroom name"))
        self.status.setHtml(_translate("deletedialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:10pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Connecting...</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deletedialog = QtWidgets.QDialog()
    ui = Ui_deletedialog()
    ui.setupUi(deletedialog)
    deletedialog.show()
    sys.exit(app.exec_())
