# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/gui/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import concurrent.futures


class Ui_home(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(512, 288)
        home.setMaximumSize(QtCore.QSize(512, 288))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        home.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/c/ff.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        home.setWindowIcon(icon)
        home.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(200, 200, 200);\n"
"font: 75 10pt \"Consolas\";")
        self.centralwidget = QtWidgets.QWidget(home)
        self.centralwidget.setObjectName("centralwidget")
        self.registerr = QtWidgets.QPushButton(self.centralwidget)
        self.registerr.setGeometry(QtCore.QRect(190, 10, 128, 32))
        self.registerr.setObjectName("registerr")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(190, 50, 128, 32))
        self.login.setObjectName("login")
        self.enterchat = QtWidgets.QPushButton(self.centralwidget)
        self.enterchat.setGeometry(QtCore.QRect(190, 130, 128, 32))
        self.enterchat.setObjectName("enterchat")
        self.makechat = QtWidgets.QPushButton(self.centralwidget)
        self.makechat.setGeometry(QtCore.QRect(190, 170, 128, 32))
        self.makechat.setObjectName("makechat")
        self.deletechat = QtWidgets.QPushButton(self.centralwidget)
        self.deletechat.setGeometry(QtCore.QRect(190, 210, 128, 32))
        self.deletechat.setObjectName("deletechat")
        self.joinchat = QtWidgets.QPushButton(self.centralwidget)
        self.joinchat.setGeometry(QtCore.QRect(190, 90, 128, 32))
        self.joinchat.setObjectName("joinchat")
        self.status = QtWidgets.QTextBrowser(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(0, 230, 128, 16))
        self.status.setStyleSheet("color: rgb(255, 0, 0);")
        self.status.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.status.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.status.setObjectName("status")
        home.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(home)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 512, 20))
        self.menubar.setObjectName("menubar")
        home.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(home)
        self.statusbar.setObjectName("statusbar")
        home.setStatusBar(self.statusbar)
        

        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)

    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "Home"))
        self.registerr.setText(_translate("home", "[Register]"))
        self.login.setText(_translate("home", "[Login]"))
        self.enterchat.setText(_translate("home", "[Enter Chatroom]"))
        self.makechat.setText(_translate("home", "[Make Chatroom]"))
        self.deletechat.setText(_translate("home", "[Delete Chatroom]"))
        self.joinchat.setText(_translate("home", "[Join]"))
        self.status.setHtml(_translate("home", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:10pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Connecting...</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    home = QtWidgets.QMainWindow()
    ui = Ui_home()
    ui.setupUi(home)
    home.show()
    sys.exit(app.exec_())
