# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'G:/gui/login.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_logindialog(object):
    def setupUi(self, logindialog):
        logindialog.setObjectName("logindialog")
        logindialog.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:/c/ff.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        logindialog.setWindowIcon(icon)
        logindialog.setStyleSheet("color: rgb(200, 200, 200);\n"
"background-color: rgb(0, 0, 0);\n"
"font: 75 10pt \"Consolas\";")
        self.buttonBox = QtWidgets.QDialogButtonBox(logindialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.username = QtWidgets.QLineEdit(logindialog)
        self.username.setGeometry(QtCore.QRect(70, 80, 256, 32))
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.password = QtWidgets.QLineEdit(logindialog)
        self.password.setGeometry(QtCore.QRect(70, 140, 256, 32))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(logindialog)
        self.label.setGeometry(QtCore.QRect(180, 10, 51, 16))
        self.label.setObjectName("label")
        self.status = QtWidgets.QTextBrowser(logindialog)
        self.status.setGeometry(QtCore.QRect(0, 280, 128, 16))
        self.status.setStyleSheet("color: rgb(255, 0, 0);")
        self.status.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.status.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.status.setObjectName("status")

        self.retranslateUi(logindialog)
        self.buttonBox.accepted.connect(logindialog.accept) # type: ignore
        self.buttonBox.rejected.connect(logindialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(logindialog)

    def retranslateUi(self, logindialog):
        _translate = QtCore.QCoreApplication.translate
        logindialog.setWindowTitle(_translate("logindialog", "Login"))
        self.username.setPlaceholderText(_translate("logindialog", " Enter Username"))
        self.password.setPlaceholderText(_translate("logindialog", " Enter Password"))
        self.label.setText(_translate("logindialog", "[Login]"))
        self.status.setHtml(_translate("logindialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:10pt; font-weight:72; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Connecting...</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    logindialog = QtWidgets.QDialog()
    ui = Ui_logindialog()
    ui.setupUi(logindialog)
    logindialog.show()
    sys.exit(app.exec_())
